### ISSUE TITLE
DPI dashboard not working: "InfluxDB Error: unsupported spread iterator type: *query.stringInterruptIterator"

### ISSUE THREAD

**Issue by JaviSoto** [unpoller/dashboards#20]
Hi! Amazing project :) Thank you so much for all the work you folks have put into this!

I have all the dashboards working, except for the DPI one. I havb `UP_UNIFI_DEFAULT_SAVE_DPI` set to `true`, and that seems to be working fine, since I see this in the unpoller logs in docker:

```
2022/12/25 04:43:47 [INFO]    => Save Sites true / Save DPI true (metrics)
```

I also have DPI enabled in UnifiOS: 

<img width="390" alt="image" src="https://user-images.githubusercontent.com/666807/209457717-5c1a5a54-abb4-40cc-a637-ca47223a83cb.png">

However, I see these errors in Graphana:

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/666807/209457702-d509007c-d5cf-4986-a6d2-251e23eef382.png">

I have influxdb v 1.8.4 as recommended in the docs. I couldn't find any reference to this error anywhere else, so I'm not sure what i could be missing.

Thanks in advance!

**Comment by JaviSoto** [comment]
I narrowed down the issue to the DPI tables having the wrong field types:

![image](https://user-images.githubusercontent.com/666807/209461082-2224025c-1ffd-42bc-a0e5-5bea9e1f36d0.jpeg)

The dashboard queries those fields with `mean()`, which fails because the values are not numeric

**Comment by JaviSoto** [comment]
Using Chronograph I saw the values seem to be getting sent incorrectly from Unpoller perhaps, there are 2 values for each one.

![image](https://user-images.githubusercontent.com/666807/209461126-bf995c83-0200-4620-9cba-caa73a7520a0.jpeg)

**Comment by JaviSoto** [comment]
It seems it may have been introduce by https://github.com/unpoller/unpoller/pull/475

**Comment by platinummonkey** [comment]
Ah thanks! Will fix sometime this week. I’m out for the holiday

**Comment by JaviSoto** [comment]
No worries! Thanks a lot! Now that I know when it was probably introduced I'll just try downgrading to a version before that temporarily. Happy holidays!!

**Comment by platinummonkey** [comment]
should be fixed in v2.7.9

**Comment by platinummonkey** [comment]
this is fixed in `v2.7.10` , there was one last fix.

noteably there is a fix on influx to fix the data:

```
drop series from clientdpi;
drop series from sitesdpi;
```

after the next poll you'll see correct data

```
> show field keys from clientdpi;
name: clientdpi
fieldKey   fieldType
--------   ---------
rx_bytes   float
rx_packets float
tx_bytes   float
tx_packets float
```

**Comment by JaviSoto** [comment]
Thank you so much!

**Comment by TheLucidOne** [comment]
Thank you.  The sitedpi query on the site dashboard is still type string.  I don’t have ‘sitesdpi’ - i have ‘sitedpi’.  

> show field keys from clientdpi                                                
name: clientdpi                                                                 
fieldKey   fieldType                                                            
--------   ---------                                                            
rx_bytes   float                                                                
rx_packets float                                                                
tx_bytes   float                                                                
tx_packets float   
                                                             
> show field keys from sitedpi                                                  
name: sitedpi                                                                   
fieldKey   fieldType                                                            
--------   ---------                                                            
rx_bytes   string                                                               
rx_packets string                                                               
tx_bytes   string                                                               
tx_packets string

**Comment by TheLucidOne** [comment]
ThAnk you.  ‘clientdpi’ looks good. I don’t have ‘sitesdpi’ - i have ‘sitedpi’ which still shows string?

`> show field keys from clientdpi                                                                                                                                            name: clientdpi                `                                                 
fieldKey   fieldType                                                            
--------   ---------                                                          
rx_bytes   float                                                                
rx_packets float                                                                
tx_bytes   float                                                                
tx_packets float   ‘

**Comment by TheLucidOne** [comment]
Thank you.   Client DPI works great now.  I don’t have ‘sitesdpi’ but i do have ‘sitedpi’ and it still shows type string, not float?

**Comment by platinummonkey** [comment]
Yup drop series from that
